# Конфигурация плагина CustomX

# Основные настройки
settings:
  # Включить вывод отладочной информации в консоль
  debug: false
  # Префикс для сообщений плагина
  prefix: '&6[CustomX] &r'
  
# Настройки зон
zones:
  # Автоматически сохранять зоны при изменении
  auto-save: true
  # Интервал автоматического обновления зон для игроков (в тиках, 20 тиков = 1 секунда)
  update-interval: 10
  
# Настройки эффектов и починки
effects:
  # Настройки по умолчанию для новых зон с эффектами
  default:
    # Показывать частицы эффектов
    show-particles: true
    # Показывать иконки эффектов
    show-icons: true
    # Делать эффекты фоновыми (ambient)
    ambient: false
  
# Настройки починки предметов
repair:
  # Настройки по умолчанию для новых зон починки
  default:
    # Интервал починки в секундах (0 = только при входе/выходе)
    interval: 0
    
    # Уведомлять игрока о починке предметов
    # true - показывать сообщение о починке
    # false - не показывать сообщение о починке
    notify: true
    
    # Звуковой эффект при починке
    # Укажите название звука из Bukkit Sound enum
    # Примеры: ENTITY_EXPERIENCE_ORB_PICKUP, ENTITY_PLAYER_LEVELUP
    # Чтобы отключить звук, укажите пустую строку '' или 'NONE'
    sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
    
# Настройки интеграции с bStats
metrics:
  # Включить сбор анонимной статистики
  enabled: true